{
    double Q2[2000], R[2000],dR[2000], chi2[2000];
    double Q2_1[2000], Q2_2[2000], Q2_3[2000], Q2_4[2000];
    double R_1[2000], R_2[2000], R_3[2000], R_4[2000];
    double dR_1[2000], dR_2[2000], dR_3[2000], dR_4[2000];
    double chi2_1[2000], chi2_2[2000], chi2_3[2000], chi2_4[2000];
    int count[4];
    double weighted_center[4];
    double weighted_bar[4];


    ifstream inFile[5];
    TGraphErrors *gr[5];
    TGraph *fr[5];
    inFile[0].open("R_fit_Mainz_Carl_norm.dat");
    inFile[1].open("R_fit_Mainz_RS.dat");
    inFile[2].open("R_fit_Mainz_global.dat");
    inFile[3].open("R_fit_PRad.dat");
    inFile[4].open("R_fit_PRad_0.0038.dat");
    for (int i=0; i<5; i++){
        inFile[i]>>count[i];
        double sum_center = 0.0;
        double sum_bar = 0.0;
        for (int j=0; j<count[i]; j++){
            inFile[i]>>Q2[j]>>R[j]>>dR[j]>>chi2[j];
            sum_bar = sum_bar + 1/pow(dR[j],2);
            sum_center = sum_center + R[j]/pow(dR[j],2);
        }
        inFile[i].close();
        gr[i] = new TGraphErrors(count[i], Q2, R, 0, dR);
        fr[i] = new TGraph(count[i], Q2, chi2);
        weighted_bar[i] = TMath::Sqrt(1/sum_center);
        weighted_center[i] = sum_center/sum_bar;
    }


    TCanvas* c1 = new TCanvas("c1", "c1", 1000, 800);
    c1->SetBottomMargin(0.15);
    c1->SetLeftMargin(0.15);
    c1->SetRightMargin(0.05);


    //=============Mainz===============
    gr[0]->SetTitle("");
    gr[0]->GetXaxis()->SetLabelSize(0.045);
    gr[0]->GetYaxis()->SetLabelSize(0.045);
    gr[0]->GetXaxis()->SetTitleSize(0.055);
    gr[0]->GetYaxis()->SetTitleSize(0.055);
    gr[0]->GetYaxis()->SetTitle("r_{fit} [fm]");
    gr[0]->GetXaxis()->SetTitle("Q^{2}_{max} [(GeV/c)^{2}]");
    gr[0]->GetYaxis()->CenterTitle();
    gr[0]->GetXaxis()->CenterTitle();
    gr[0]->GetXaxis()->SetTitleFont(62);
    gr[0]->GetXaxis()->SetLabelFont(62);
    gr[0]->GetYaxis()->SetTitleFont(62);
    gr[0]->GetYaxis()->SetLabelFont(62);
    gr[0]->GetYaxis()->SetTitleOffset(1.1);
    gr[0]->GetXaxis()->SetLimits(0.0, 0.61);
    gr[0]->GetYaxis()->SetRangeUser(0.4, 1.0);
    //gr[0]->Draw("AP");
    gr[0]->SetMarkerStyle(20);
    gr[0]->SetMarkerSize(1.2);
    gr[0]->SetMarkerColor(1);
    gr[0]->SetLineColor(1);
    gr[0]->SetLineWidth(2.5);
    //gr[1]->Draw("Psame");
    gr[1]->SetMarkerStyle(24);
    gr[1]->SetMarkerSize(1.4);
    gr[1]->SetMarkerColor(2);
    gr[1]->SetLineColor(2);
    gr[1]->SetLineWidth(2.5);
    //gr[2]->Draw("Psame");
    gr[2]->SetMarkerStyle(25);
    gr[2]->SetMarkerSize(1.4);
    gr[2]->SetMarkerColor(4);
    gr[2]->SetLineColor(4);
    gr[2]->SetLineWidth(2.5);
    //=============Mainz_chi2===============
    fr[0]->SetTitle("");
    fr[0]->GetXaxis()->SetLabelSize(0.045);
    fr[0]->GetYaxis()->SetLabelSize(0.045);
    fr[0]->GetXaxis()->SetTitleSize(0.055);
    fr[0]->GetYaxis()->SetTitleSize(0.055);
    fr[0]->GetYaxis()->SetTitle("#chi^{2}/dof");
    fr[0]->GetXaxis()->SetTitle("Q^{2}_{max} [(GeV/c)^{2}]");
    fr[0]->GetYaxis()->CenterTitle();
    fr[0]->GetXaxis()->CenterTitle();
    fr[0]->GetXaxis()->SetTitleFont(62);
    fr[0]->GetXaxis()->SetLabelFont(62);
    fr[0]->GetYaxis()->SetTitleFont(62);
    fr[0]->GetYaxis()->SetLabelFont(62);
    fr[0]->GetYaxis()->SetTitleOffset(1.1);
    fr[0]->GetXaxis()->SetLimits(0.0, 0.61);
    fr[0]->GetYaxis()->SetRangeUser(0.5, 3.0);
    fr[0]->Draw("AP");
    fr[0]->SetMarkerStyle(20);
    fr[0]->SetMarkerSize(1.2);
    fr[0]->SetMarkerColor(1);
    fr[0]->SetLineColor(1);
    fr[0]->SetLineWidth(2.5);
    fr[1]->Draw("Psame");
    fr[1]->SetMarkerStyle(20);
    fr[1]->SetMarkerSize(1.2);
    fr[1]->SetMarkerColor(2);
    fr[1]->SetLineColor(2);
    fr[1]->SetLineWidth(2.5);
    fr[2]->Draw("Psame");
    fr[2]->SetMarkerStyle(20);
    fr[2]->SetMarkerSize(1.2);
    fr[2]->SetMarkerColor(4);
    fr[2]->SetLineColor(4);
    fr[2]->SetLineWidth(2.5);
    TLegend* leg = new TLegend(0.23, 0.18, 0.93, 0.35);
    leg->AddEntry(fr[0], "Rational (1,1) fit with GE from Carlson et al.", "p");
    leg->AddEntry(fr[1], "Rational (1,1) fit with GE from RS by Bernauer", "p");
    leg->AddEntry(fr[2], "Rational (1,1) fit with cross section", "p");
    //leg->Draw("same");
    TLine* line_chi2;
    line_chi2 = new TLine(0.0, 1.0, 0.61, 1.0);
    line_chi2->SetLineWidth(1.4);
    line_chi2->SetLineStyle(9);
    line_chi2->SetLineColor(13);
    line_chi2->Draw("same");
    //=========PRad============
    gr[3]->SetTitle("");
    gr[3]->GetXaxis()->SetLabelSize(0.045);
    gr[3]->GetYaxis()->SetLabelSize(0.045);
    gr[3]->GetXaxis()->SetTitleSize(0.055);
    gr[3]->GetYaxis()->SetTitleSize(0.055);
    gr[3]->GetYaxis()->SetTitle("r_{fit} [fm]");
    gr[3]->GetXaxis()->SetTitle("Q^{2}_{max} [(GeV/c)^{2}]");
    gr[3]->GetYaxis()->CenterTitle();
    gr[3]->GetXaxis()->CenterTitle();
    gr[3]->GetXaxis()->SetTitleFont(62);
    gr[3]->GetXaxis()->SetLabelFont(62);
    gr[3]->GetYaxis()->SetTitleFont(62);
    gr[3]->GetYaxis()->SetLabelFont(62);
    gr[3]->GetYaxis()->SetTitleOffset(1.1);
    gr[3]->GetXaxis()->SetLimits(0.0, 0.062);
    gr[3]->GetYaxis()->SetRangeUser(0.73, 0.90);
    //gr[3]->Draw("AP");
    //gr[3]->Draw("Psame");
    gr[3]->SetMarkerStyle(22);
    gr[3]->SetMarkerSize(1.2);
    gr[3]->SetMarkerColor(4);
    gr[3]->SetLineColor(4);
    gr[3]->SetLineWidth(2.5);
    //gr[4]->Draw("Psame");
    gr[4]->SetMarkerStyle(25);
    gr[4]->SetMarkerSize(1.2);
    gr[4]->SetMarkerColor(6);
    gr[4]->SetLineColor(6);
    gr[4]->SetLineWidth(2.5);
    TLegend* leg = new TLegend(0.23, 0.23, 0.93, 0.43);
    leg->AddEntry(gr[0], "Rational (1,1) fit with GE from Carlson et al.", "ep");
    leg->AddEntry(gr[1], "Rational (1,1) fit with GE from RS by Bernauer", "ep");
    leg->AddEntry(gr[2], "Rational (1,1) fit with cross section", "ep");
    //TLegend* leg = new TLegend(0.44, 0.23, 0.93, 0.43);
    //leg->AddEntry(gr[3], "PRad", "ep");
    //leg->AddEntry(gr[4], "PRad start from 0.0038 GeV^{2}", "ep");
    //leg->SetTextSize(0.035);
    //leg->Draw("same");

    TLine* line[2];
    line[0] = new TLine(0.0, weighted_center[0], 0.6, weighted_center[0]);
    line[1] = new TLine(0.0, weighted_center[1], 0.6, weighted_center[1]);
    line[0]->SetLineWidth(1);
    line[0]->SetLineColor(1);
    //line[0]->Draw("same");
    line[1]->SetLineWidth(1);
    line[1]->SetLineColor(2);
    //line[1]->Draw("same");
    //line[0] = new TLine(0.0, weighted_center[3], 0.062, weighted_center[3]);
    //line[1] = new TLine(0.0, weighted_center[4], 0.062, weighted_center[4]);
    //line[0]->SetLineWidth(1);
    //line[0]->SetLineColor(4);
    //line[0]->Draw("same");
    //line[1]->SetLineWidth(1);
    //line[1]->SetLineColor(6);
    //line[1]->Draw("same");
    TBox* MainzBox1 = new TBox(0.0, weighted_center[0]-weighted_bar[0], 0.6, weighted_center[0]+weighted_bar[0]);
    MainzBox1->SetFillStyle(3001);
    MainzBox1->SetFillColorAlpha(14, 0.3);
    TBox* MainzBox2 = new TBox(0.0, weighted_center[1]-weighted_bar[1], 0.6, weighted_center[1]+weighted_bar[1]);
    MainzBox2->SetFillStyle(3001);
    MainzBox2->SetFillColorAlpha(45, 0.3);
    //MainzBox1->Draw("same");
    //MainzBox2->Draw("same");

    TBox* PRadBox1 = new TBox(0.0, weighted_center[2]-weighted_bar[2], 0.062, weighted_center[2]+weighted_bar[2]);
    PRadBox1->SetFillStyle(3001);
    PRadBox1->SetFillColorAlpha(4, 0.3);
    TBox* PRadBox2 = new TBox(0.0, weighted_center[3]-weighted_bar[3], 0.062, weighted_center[3]+weighted_bar[3]);
    PRadBox2->SetFillStyle(3001);
    PRadBox2->SetFillColorAlpha(6, 0.3);
    //PRadBox1->Draw("same");
    //PRadBox2->Draw("same");

}
